version: '3.8'

services:
  php:
    build: .
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: bash -c "composer install && tail -f /dev/null"
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:latest
    ports:
      - "16379:6379"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
